local_costmap:
  #Independent settings for the local costmap
  map_type: voxel
  publish_voxel_map: true
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
  origin_z: -0.01
  z_resolution: 0.2
  z_voxels: 10
