planner_configs:
  SBLkConfig1:
    type: kinematic::SBL
  LBKPIECEkConfig1:
    type: kinematic::LBKPIECE
  LazyRRTkConfig1:
    type: kinematic::LazyRRT
  RTTStarConfig1:
    type: kinematic::RRTStar
groups:
  - both_arms
  - left_arm
  - left_arm_cartesian
  - right_arm
  - right_arm_torso
  - right_arm_cartesian
  - upper_body
both_arms:
  planner_type: JointPlanner
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
    - RTTStarConfig1
    - LazyRRTkConfig1
  projection_evaluator: joint_state
left_arm:
  planner_type: JointPlanner
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
    - RTTStarConfig1
    - LazyRRTkConfig1
  projection_evaluator: joint_state
right_arm:
  planner_type: JointPlanner
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
    - RTTStarConfig1
    - LazyRRTkConfig1
  projection_evaluator: joint_state
right_arm_torso:
  planner_type: JointPlanner
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
    - RTTStarConfig1
    - LazyRRTkConfig1
  projection_evaluator: joint_state
upper_body:
  planner_type: JointPlanner
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
    - RTTStarConfig1
    - LazyRRTkConfig1
  projection_evaluator: joint_state
left_arm_cartesian:
  parent_frame: torso_2_link
  physical_group: left_arm
  planner_type: RPYIKTaskSpacePlanner
  state_spaces:
    - x
    - y
    - z
    - roll
    - pitch
    - yaw
  x:
    type: Linear
    min: -2.0
    max: 2.0
  y:
    type: Linear
    min: -2.0
    max: 2.0
  z:
    type: Linear
    min: -2.0
    max: 2.0
  roll:
    type: Revolute
  pitch:
    type: Revolute
  yaw:
    type: Revolute
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
    - RTTStarConfig1
    - LazyRRTkConfig1
  kinematics_solver: arm_kinematics_constraint_aware/KDLArmKinematicsPlugin
  tip_name: arm_left_7_link
  root_name: torso_2_link
  projection_evaluator: joint_state
  longest_valid_segment_fraction: 0.001
right_arm_cartesian:
  parent_frame: torso_2_link
  physical_group: right_arm
  planner_type: RPYIKTaskSpacePlanner
  state_spaces:
    - x
    - y
    - z
    - roll
    - pitch
    - yaw
  x:
    type: Linear
    min: -2.0
    max: 2.0
  y:
    type: Linear
    min: -2.0
    max: 2.0
  z:
    type: Linear
    min: -2.0
    max: 2.0
  roll:
    type: Revolute
  pitch:
    type: Revolute
  yaw:
    type: Revolute
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
    - RTTStarConfig1
    - LazyRRTkConfig1
  kinematics_solver: arm_kinematics_constraint_aware/KDLArmKinematicsPlugin
  tip_name: arm_right_7_link
  root_name: torso_2_link
  projection_evaluator: joint_state
  longest_valid_segment_fraction: 0.001
right_arm_torso_cartesian:
  parent_frame: base_link
  physical_group: right_arm
  planner_type: RPYIKTaskSpacePlanner
  state_spaces:
    - x
    - y
    - z
    - roll
    - pitch
    - yaw
  x:
    type: Linear
    min: -2.0
    max: 2.0
  y:
    type: Linear
    min: -2.0
    max: 2.0
  z:
    type: Linear
    min: -2.0
    max: 2.0
  roll:
    type: Revolute
  pitch:
    type: Revolute
  yaw:
    type: Revolute
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
    - RTTStarConfig1
    - LazyRRTkConfig1
  kinematics_solver: reem_kinematics_constraint_aware/ReemArmKinematicsPlugin
  tip_name: arm_right_7_link
  root_name: base_link
  projection_evaluator: joint_state
  longest_valid_segment_fraction: 0.001