min_sensor_dist: .05
self_see_default_padding: .01
self_see_default_scale: 1.0
self_see_links:
  - name: base_link
    padding: 0.02

  - name: torso_2_link
    padding: 0.02

  - name: arm_right_1_link
    padding: 0.04
  - name: arm_right_2_link
    padding: 0.04
  - name: arm_right_3_link
    padding: 0.04
  - name: arm_right_4_link
    padding: 0.04
  - name: arm_right_5_link
    padding: 0.04
  - name: arm_right_6_link
    padding: 0.04
  - name: arm_right_7_link
    padding: 0.04

  - name: arm_left_1_link
    padding: 0.04
  - name: arm_left_2_link
    padding: 0.04
  - name: arm_left_3_link
    padding: 0.04
  - name: arm_left_4_link
    padding: 0.04
  - name: arm_left_5_link
    padding: 0.04
  - name: arm_left_6_link
    padding: 0.04
  - name: arm_left_7_link
    padding: 0.04

  - name: hand_right_palm_link
    padding: 0.04
  - name: hand_right_thumb_link
    padding: 0.04
  - name: hand_right_index_1_link
    padding: 0.04
  - name: hand_right_index_2_link
    padding: 0.04
  - name: hand_right_index_3_link
    padding: 0.04
  - name: hand_right_middle_1_link
    padding: 0.04
  - name: hand_right_middle_2_link
    padding: 0.04
  - name: hand_right_middle_3_link
    padding: 0.04

  - name: hand_left_palm_link
    padding: 0.04
  - name: hand_left_thumb_link
    padding: 0.04
  - name: hand_left_index_1_link
    padding: 0.04
  - name: hand_left_index_2_link
    padding: 0.04
  - name: hand_left_index_3_link
    padding: 0.04
  - name: hand_left_middle_1_link
    padding: 0.04
  - name: hand_left_middle_2_link
    padding: 0.04
  - name: hand_left_middle_3_link
    padding: 0.04
