play_motion:
  controllers: [fake_controller]
  motions:
    say_hi:
      joints: [fake_joint_2, fake_joint_1]
      points:
      - positions: [-0.4, 0.2]
        time_from_start: 0.0
      - positions: [-0.4, -0.2]
        time_from_start: 1.0
      - positions: [-0.4, 0.2]
        time_from_start: 2.0
