transform_tolerance: 0.2
obstacle_range: 3.0
raytrace_range: 2.5
robot_radius: 0.35
inflation_radius: 0.45 

observation_sources: base_scan sonar_cloud #vos #inclined_cloud

base_scan: {sensor_frame: base_laser_link, data_type: LaserScan, topic: scan_filtered, expected_update_rate: 0.3,
  observation_persistence: 0.0, marking: true, clearing: true, min_obstacle_height: -0.1, max_obstacle_height: 0.2}

vos: {sensor_frame: map, data_type: PointCloud, topic: vo_cloud , expected_update_rate: 12.0, 
  observation_persistence: 0.0, marking: true, clearing: false, obstacle_range: 50.0, min_obstacle_height: 0.0, max_obstacle_height: 2.0}

inclined_cloud: {sensor_frame: base_torso_laser_link, data_type: PointCloud2, topic: hokuyo_cloud , expected_update_rate: 1.0,
  observation_persistence: 0.0, marking: true, clearing: true, min_obstacle_height: 0.31, max_obstacle_height: 0.8}

# Note that the obstacle and raytrace are defined in order to avoid taht the sonars readings remove the laser ones.
sonar_cloud: {sensor_frame: base_link, data_type: PointCloud2, topic: sonar_cloud, expected_update_rate: 1.0,
  observation_persistence: 0.0, marking: true, clearing: true, min_obstacle_height: 0.1, max_obstacle_height: 1.8,
  obstacle_range: 3.0, raytrace_range: 1.0}
