#Independent settings for the planner's costmap
global_costmap: 
  map_topic: map
  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 1.0
  publish_frequency: 0.0
  static_map: true
  robot_radius: 0.8
  inflation_radius: 0.81

